name: Deploy PokeAPI to Cloud Run

on:
  push:
    branches:
      - main  

env:
  PROJECT_ID: "gcp-pokeapi"     
  PROJECT_NUMBER: "1083246166320"
  REGION: "us-central1"
  SERVICE_NAME: "pokeapi-service"
  SERVICE_ACCOUNT: "gcp-service@gcp-pokeapi.iam.gserviceaccount.com"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Autenticación con Google Cloud
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          # Asegúrate de que esta ruta sea exacta en tu consola de GCP
          workload_identity_provider: 'projects/1083246166320/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: ${{ env.SERVICE_ACCOUNT }}

      # 2. Autenticar Docker específicamente para GCR (usando el token de WIF)
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: ${{ steps.auth.outputs.access_token }}
          registry: gcr.io

      # 3. Construir y Subir la imagen
      # Usamos el 'setup-gcloud' para asegurar que los comandos gcloud funcionen después
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Container
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # 4. Desplegar en Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --quiet \
            --allow-unauthenticated
